name: Temp Workflow

on:
  workflow_dispatch:

jobs:
  build:
    env:
      is_null: "IS NULL"
      not_is_null: "NOT IS NULL"
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ VARS.TEST == null && env.is_null ||  env.not_is_null }}
      - run: echo ${{ toJSON(VARS.TEST_JSON) }}
      - run: echo ${{ fromJSON(VARS.TEST_JSON) }}
      - run: echo ${{ fromJSON(VARS.TEST_JSON) }}
      - run: echo ${{ fromJSON(VARS) }}