name: Temp Workflow

on:
  workflow_dispatch:

jobs:
  build:
    env:
      is_null: "IS NULL"
      not_is_null: "NOT IS NULL"
    runs-on: ubuntu-latest
    steps:
      - name: 1
        run: echo ${{ VARS.TEST == null && env.is_null ||  env.not_is_null }}
      - name: 2
        run: echo ${{ toJSON(VARS.TEST_JSON) }}
      - name: 3
        run: echo ${{ toJSON(VARS.TEST_JSON).test }}
      - name: 4
        run: echo ${{ fromJSON(VARS.TEST_JSON) }}
      - name: 5
        run: echo ${{ fromJSON(VARS.TEST_JSON).test }}
      - name: 6
        run: echo ${{ VARS.TEST_JSON.test }}
      - name: 7
        run: echo ${{ toJSON(VARS.JSON_2) }}
      - name: 8
        run: echo ${{ fromJSON(VARS.JSON_2) }}
      - name: 9
        run: echo ${{ VARS }}
      - name: 10
        run: echo ${{ toJSON(VARS) }}