name: Environment
on:
  workflow_dispatch:
env:
  Greeting: "Hello World!!"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo " ${{ env.Greeting }}"
    - run: echo " ${{env.Greeting}}"
