on:
  workflow_dispatch:

name: SonarQube Scan
jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Unit test
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run test
      - uses: actions/upload-artifact@v3
        name: Store code coverage report
        with:
          name: code-coverage-report
          path: TestResults

  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    needs: ["unit-test"]
    steps:
      - name: Checking out
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./
          args: >
            -Dproject.settings=./sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
